exports.capitalCities = [
    {city: `Kabul`, name: `Afghanistan`, difficulty: 2},
    {city: `Mariehamn`, name: `Åland Islands`, difficulty: 4},
    {city: `Tirana`, name: `Albania`, difficulty: 2},
    {city: `Algiers`, name: `Algeria`, difficulty: 1},
    {city: `Pago Pago`, name: `American Samoa`, difficulty: 4},
    {city: `Andorra la Vella`, name: `Andorra`, difficulty: 2},
    {city: `Luanda`, name: `Angola`, difficulty: 3},
    {city: `The Valley`, name: `Anguilla`, difficulty: 4},
    {city: `St. John's`, name: `Antigua and Barbuda`, difficulty: 4},
    {city: `Buenos Aires`, name: `Argentina`, difficulty: 2},
    {city: `Yerevan`, name: `Armenia`, difficulty: 3},
    {city: `Oranjestad`, name: `Aruba`, difficulty: 4},
    {city: `Canberra`, name: `Australia`, difficulty: 1},
    {city: `Vienna`, name: `Austria`, difficulty: 2},
    {city: `Baku`, name: `Azerbaijan`, difficulty: 3},
   
    {city: `Nassau`, name: `Bahamas`, difficulty: 3},
    {city: `Manama`, name: `Bahrain`, difficulty: 2},
    {city: `Dhaka`, name: `Bangladesh`, difficulty: 2},
    {city: `Bridgetown`, name: `Barbados`, difficulty: 3},
    {city: `Minsk`, name: `Belarus`, difficulty: 2},
    {city: `Brussels`, name: `Belgium`, difficulty: 1},
    {city: `Belmopan`, name: `Belize`, difficulty: 3},
    {city: `Porto-Novo`, name: `Benin`, difficulty: 4},
    {city: `Hamilton`, name: `Bermuda`, difficulty: 4},
    {city: `Thimphu`, name: `Bhutan`, difficulty: 3},
    {city: `La Paz`, name: `Bolivia`, difficulty: 3},
    {city: `Sarajevo`, name: `Bosnia and Herzegovina`, difficulty: 2},
    {city: `Gaborone`, name: `Botswana`, difficulty: 3},
    {city: `Brasilia`, name: `Brazil`, difficulty: 1},
    {city: `Road Town`, name: `British Virgin Islands`, difficulty: 4},
    {city: `Camp Justice`, name: `British Indian Ocean Territory`, difficulty: 4},
    {city: `Bandar Seri Begawan`, name: `Brunei`, difficulty: 4},
    {city: `Sofia`, name: `Bulgaria`, difficulty: 2},
    {city: `Ouagadougou`, name: `Burkina Faso`, difficulty: 4},
    {city: `Gitega`, name: `Burundi`, difficulty: 3},
    {city: `Kralendijk`, name: `Bonaire`, difficulty: 4},
    
    {city: `Phnom Penh`, name: `Cambodia`, difficulty: 3},
    {city: `Yaounde`, name: `Cameroon`, difficulty: 3},
    {city: `Ottawa`, name: `Canada`, difficulty: 2},
    {city: `Praia`, name: `Cape Verde`, difficulty: 4},
    {city: `George Town`, name: `Cayman Islands`, difficulty: 4},
    {city: `Bangui`, name: `Central African Republic`, difficulty: 3},
    {city: `N'Djamena`, name: `Chad`, difficulty: 3},
    {city: `Santiago`, name: `Chile`, difficulty: 2},
    {city: `Beijing`, name: `China`, difficulty: 0},
    {city: `Hong Kong`, name: `Hong Kong`, difficulty: 0},
    {city: `Macau`, name: `Macau`, difficulty: 1},
    {city: `Flying Fish Cove`, name: `Christmas Island`, difficulty: 4},
    {city: `West Island`, name: `Cocos Keeling Islands`, difficulty: 4},
    {city: `Bogota`, name: `Colombia`, difficulty: 2},
    {city: `Moroni`, name: `Comoros`, difficulty: 4},
    {city: `Brazzaville`, name: `Congo`, difficulty: 3},
    {city: `Kinshasa`, name: `Democratic Republic of Congo`, difficulty: 3},
    {city: `Avarua`, name: `Cook Islands`, difficulty: 4},
    {city: `San Jose`, name: `Costa Rica`, difficulty: 3},
    {city: `Yamoussoukro`, name: `Ivory Coast`, difficulty: 4},
    {city: `Zagreb`, name: `Croatia`, difficulty: 2},
    {city: `Havana`, name: `Cuba`, difficulty: 2},
    {city: `Willemstad`, name: `Curacao`, difficulty: 4},
    {city: `Nicosia`, name: `Cyprus`, difficulty: 2},
    {city: `Prague`, name: `Czech Republic`, difficulty: 2},
    {city: `Las Palmas`, name: `Canary Islands`, difficulty: 4},
    
    {city: `Copenhagen`, name: `Denmark`, difficulty: 2},
    {city: `Djibouti`, name: `Djibouti`, difficulty: 2},
    {city: `Roseau`, name: `Dominica`, difficulty: 4},
    {city: `Santo Domingo`, name: `Dominican Republic`, difficulty: 3},
    
    {city: `Quito`, name: `Ecuador`, difficulty: 3},
    {city: `Cairo`, name: `Egypt`, difficulty: 1},
    {city: `San Salvador`, name: `El Salvador`, difficulty: 3},
    {city: `Malabo`, name: `Equatorial Guinea`, difficulty: 4},
    {city: `Asmara`, name: `Eritrea`, difficulty: 3},
    {city: `Tallinn`, name: `Estonia`, difficulty: 2},
    {city: `Addis Ababa`, name: `Ethiopia`, difficulty: 2},
    {city: `Brussels`, name: `European Union`, difficulty: 1},
    
    {city: `Stanley`, name: `Falkland Islands`, difficulty: 4},
    {city: `Torshavn`, name: `Faroe Islands`, difficulty: 3},
    {city: `Suva`, name: `Fiji`, difficulty: 3},
    {city: `Helsinki`, name: `Finland`, difficulty: 2},
    {city: `Paris`, name: `France`, difficulty: 0},
    {city: `Cayenne`, name: `French Guiana`, difficulty: 4},
    {city: `Papeete`, name: `French Polynesia`, difficulty: 4},
    {city: `Saint Pierre`, name: `French Southern Territories`, difficulty: 4},
    
    {city: `Libreville`, name: `Gabon`, difficulty: 4},
    {city: `Banjul`, name: `The Gambia`, difficulty: 3},
    {city: `Tbilisi`, name: `Georgia`, difficulty: 3},
    {city: `Berlin`, name: `Germany`, difficulty: 0},
    {city: `Accra`, name: `Ghana`, difficulty: 3},
    {city: `Gibraltar`, name: `Gibraltar`, difficulty: 2},
    {city: `Athens`, name: `Greece`, difficulty: 1},
    {city: `Nuuk`, name: `Greenland`, difficulty: 3},
    {city: `St. George's`, name: `Grenada`, difficulty: 4},
    {city: `Basse-Terre`, name: `Guadeloupe`, difficulty: 4},
    {city: `Hagatna`, name: `Guam`, difficulty: 4},
    {city: `Guatemala City`, name: `Guatemala`, difficulty: 2},
    {city: `St. Peter Port`, name: `Guernsey`, difficulty: 4},
    {city: `Conakry`, name: `Guinea`, difficulty: 4},
    {city: `Bissau`, name: `Guinea-Bissau`, difficulty: 2},
    {city: `Georgetown`, name: `Guyana`, difficulty: 4},
    
    {city: `Port-au-Prince`, name: `Haiti`, difficulty: 3},
    {city: `Vatican City`, name: `Vatican City`, difficulty: 1},
    {city: `Tegucigalpa`, name: `Honduras`, difficulty: 3},
    {city: `Budapest`, name: `Hungary`, difficulty: 2},
    
    {city: `Reykjavik`, name: `Iceland`, difficulty: 3},
    {city: `New Delhi`, name: `India`, difficulty: 0},
    {city: `Jakarta`, name: `Indonesia`, difficulty: 1},
    {city: `Tehran`, name: `Iran`, difficulty: 1},
    {city: `Baghdad`, name: `Iraq`, difficulty: 2},
    {city: `Dublin`, name: `Ireland`, difficulty: 2},
    {city: `Douglas`, name: `Isle of Man`, difficulty: 4},
    {city: `Jerusalem`, name: `Israel`, difficulty: 1},
    {city: `Rome`, name: `Italy`, difficulty: 0},
    
    {city: `Kingston`, name: `Jamaica`, difficulty: 2},
    {city: `Tokyo`, name: `Japan`, difficulty: 0},
    {city: `St. Helier`, name: `Jersey`, difficulty: 4},
    {city: `Amman`, name: `Jordan`, difficulty: 2},
    
    {city: `Nur-Sultan`, name: `Kazakhstan`, difficulty: 2},
    {city: `Nairobi`, name: `Kenya`, difficulty: 3},
    {city: `Tarawa`, name: `Kiribati`, difficulty: 4},
    {city: `Pyongyang`, name: `North Korea`, difficulty: 1},
    {city: `Seoul`, name: `South Korea`, difficulty: 0},
    {city: `Kuwait City`, name: `Kuwait`, difficulty: 1},
    {city: `Bishkek`, name: `Kyrgyzstan`, difficulty: 3},
    
    {city: `Vientiane`, name: `Laos`, difficulty: 4},
    {city: `Riga`, name: `Latvia`, difficulty: 2},
    {city: `Beirut`, name: `Lebanon`, difficulty: 2},
    {city: `Maseru`, name: `Lesotho`, difficulty: 4},
    {city: `Monrovia`, name: `Liberia`, difficulty: 3},
    {city: `Tripoli`, name: `Libya`, difficulty: 2},
    {city: `Vaduz`, name: `Liechtenstein`, difficulty: 4},
    {city: `Vilnius`, name: `Lithuania`, difficulty: 2},
    {city: `Luxembourg`, name: `Luxembourg`, difficulty: 1},
    
    {city: `Skopje`, name: `North Macedonia`, difficulty: 3},
    {city: `Antananarivo`, name: `Madagascar`, difficulty: 3},
    {city: `Litongwe`, name: `Malawi`, difficulty: 4},
    {city: `Kuala Lumpur`, name: `Malaysia`, difficulty: 2},
    {city: `Male`, name: `Maldives`, difficulty: 4},
    {city: `Bamako`, name: `Mali`, difficulty: 4},
    {city: `Valletta`, name: `Malta`, difficulty: 3},
    {city: `Majuro`, name: `Marshall Islands`, difficulty: 4},
    {city: `Fort-de-France`, name: `Martinique`, difficulty: 4},
    {city: `Nouakchott`, name: `Mauritania`, difficulty: 3},
    {city: `Port Louis`, name: `Mauritius`, difficulty: 4},
    {city: `Mamoudzou`, name: `Mayotte`, difficulty: 4},
    {city: `Mexico City`, name: `Mexico`, difficulty: 0},
    {city: `Palikir`, name: `Micronesia`, difficulty: 4},
    {city: `Chisinau`, name: `Moldova`, difficulty: 3},
    {city: `Monaco`, name: `Monaco`, difficulty: 1},
    {city: `Ulaanbaatar`, name: `Mongolia`, difficulty: 2},
    {city: `Podgorica`, name: `Montenegro`, difficulty: 3},
    {city: `Plymouth`, name: `Montserrat`, difficulty: 4},
    {city: `Rabat`, name: `Morocco`, difficulty: 2},
    {city: `Maputo`, name: `Mozambique`, difficulty: 4},
    {city: `Naypyidaw`, name: `Myanmar`, difficulty: 3},
    
    {city: `Windhoek`, name: `Namibia`, difficulty: 3},
    {city: `Yaren`, name: `Nauru`, difficulty: 4},
    {city: `Kathmandu`, name: `Nepal`, difficulty: 2},
    {city: `Amsterdam`, name: `Netherlands`, difficulty: 0},
    {city: `Noumea`, name: `New Caledonia`, difficulty: 4},
    {city: `Wellington`, name: `New Zealand`, difficulty: 2},
    {city: `Managua`, name: `Nicaragua`, difficulty: 4},
    {city: `Niamey`, name: `Niger`, difficulty: 4},
    {city: `Abuja`, name: `Nigeria`, difficulty: 2},
    {city: `Alofi`, name: `Niue`, difficulty: 4},
    {city: `Kingston`, name: `Norfolk Island`, difficulty: 4},
    {city: `Saipan`, name: `Northern Mariana Islands`, difficulty: 4},
    {city: `Oslo`, name: `Norway`, difficulty: 1},
    
    {city: `Muscat`, name: `Oman`, difficulty: 2},
    
    {city: `Islamabad`, name: `Pakistan`, difficulty: 1},
    {city: `Ngerulmud`, name: `Palau`, difficulty: 4},
    {city: `East Jerusalem`, name: `Palestine`, difficulty: 2},
    {city: `Panama City`, name: `Panama`, difficulty: 1},
    {city: `Port Moresby`, name: `Papua New Guinea`, difficulty: 4},
    {city: `Asuncion`, name: `Paraguay`, difficulty: 3},
    
    {city: `Lima`, name: `Peru`, difficulty: 2},
    {city: `Manila`, name: `Philippines`, difficulty: 1},
    {city: `Adamstown`, name: `Pitcairn Islands`, difficulty: 4},
    {city: `Warsaw`, name: `Poland`, difficulty: 1},
    {city: `Lisbon`, name: `Portugal`, difficulty: 1},
    {city: `San Juan`, name: `Puerto Rico`, difficulty: 2},
    
    {city: `Doha`, name: `Qatar`, difficulty: 2},
    
    {city: `Saint-Denis`, name: `Reunion`, difficulty: 4},
    {city: `Bucharest`, name: `Romania`, difficulty: 2},
    {city: `Moscow`, name: `Russia`, difficulty: 0},
    {city: `Kigali`, name: `Rwanda`, difficulty: 3},
    
    {city: `Gustavia`, name: `Saint Barthelemy`, difficulty: 4},
    {city: `Jamestown`, name: `Saint Helena`, difficulty: 4},
    {city: `Basseterre`, name: `Saint Kitts and Nevis`, difficulty: 4},
    {city: `Castries`, name: `Saint Lucia`, difficulty: 4},
    {city: `Marigot`, name: `Saint Martin`, difficulty: 4},
    {city: `St. Pierre`, name: `Saint Pierre and Miquelon`, difficulty: 4},
    {city: `Kingstown`, name: `Saint Vincent and the Grenadines`, difficulty: 4},
    {city: `Apia`, name: `Samoa`, difficulty: 4},
    {city: `San Marino`, name: `San Marino`, difficulty: 1},
    {city: `Sao Tome`, name: `Sao Tome and Principe`, difficulty: 4},
    {city: `Riyadh`, name: `Saudi Arabia`, difficulty: 1},
    {city: `Dakar`, name: `Senegal`, difficulty: 3},
    {city: `Belgrade`, name: `Serbia`, difficulty: 2},
    {city: `Victoria`, name: `Seychelles`, difficulty: 4},
    {city: `Freetown`, name: `Sierra Leone`, difficulty: 4},
    {city: `Singapore`, name: `Singapore`, difficulty: 0},
    {city: `Bratislava`, name: `Slovakia`, difficulty: 2},
    {city: `Ljubljana`, name: `Slovenia`, difficulty: 2},
    {city: `Honiara`, name: `Solomon Islands`, difficulty: 3},
    {city: `Mogadishu`, name: `Somalia`, difficulty: 2},
    {city: `Cape Town`, name: `South Africa (Legislative)`, difficulty: 1},
    {city: `King Edward Point`, name: `South Georgia and the South Sandwich Islands`, difficulty: 4},
    {city: `Juba`, name: `South Sudan`, difficulty: 4},
    {city: `Madrid`, name: `Spain`, difficulty: 1},
    {city: `Colombo`, name: `Sri Lanka`, difficulty: 2},
    {city: `Khartoum`, name: `Sudan`, difficulty: 2},
    {city: `Paramaribo`, name: `Suriname`, difficulty: 3},
    {city: `Longyearbyen`, name: `Svalbard and Jan Mayen`, difficulty: 4},
    {city: `Mbabane`, name: `eSwatini`, difficulty: 4},
    {city: `Stockholm`, name: `Sweden`, difficulty: 1},
    {city: `Bern`, name: `Switzerland`, difficulty: 1},
    {city: `Damascus`, name: `Syria`, difficulty: 1},
    
    {city: `Taipei`, name: `Taiwan`, difficulty: 1},
    {city: `Dushanbe`, name: `Tajikistan`, difficulty: 3},
    {city: `Dodoma`, name: `Tanzania`, difficulty: 3},
    {city: `Bangkok`, name: `Thailand`, difficulty: 1},
    {city: `Dili`, name: `Timor Leste (East Timor)`, difficulty: 3},
    {city: `Lome`, name: `Togo`, difficulty: 4},
    {city: `Nukunonu`, name: `Tokelau`, difficulty: 4},
  
    {city: `Nuku'alofa`, name: `Tonga`, difficulty: 4},
    {city: `Port of Spain`, name: `Trinidad and Tobago`, difficulty: 3},
    {city: `Tunis`, name: `Tunisia`, difficulty: 2},
    {city: `Ankara`, name: `Turkey`, difficulty: 2},
    {city: `Ashgabat`, name: `Turkmenistan`, difficulty: 3},
    {city: `Cockburn Town`, name: `Turks and Caicos Islands`, difficulty: 4},
    {city: `Funafuti`, name: `Tuvalu`, difficulty: 4},
    
    {city: `Kampala`, name: `Uganda`, difficulty: 3},
    {city: `Kiev`, name: `Ukraine`, difficulty: 1},
    {city: `Abu Dhabi`, name: `United Arab Emirates`, difficulty: 1},
    {city: `London`, name: `United Kingdom`, difficulty: 0},
    {city: `Washington DC`, name: `United States of America`, difficulty: 0},
    {city: `Montevideo`, name: `Uruguay`, difficulty: 2},
    {city: `Tashkent`, name: `Uzbekistan`, difficulty: 3},
    
    {city: `Port Vila`, name: `Vanuatu`, difficulty: 4},
    {city: `Caracas`, name: `Venezuela`, difficulty: 2},
    {city: `Hanoi`, name: `Vietnam`, difficulty: 1},
    {city: `Charlotte Amalie`, name: `US Virgin Islands`, difficulty: 4},
    
    {city: `Mata-Utu`, name: `Wallis and Futuna`, difficulty: 4},
    {city: `Tifariti`, name: `Sahrawi Arab Democratic Republic`, difficulty: 4},
    
    {city: `Sana'a`, name: `Yemen`, difficulty: 2},
    
    {city: `Lusaka`, name: `Zambia`, difficulty: 3},
    {city: `Harare`, name: `Zimbabwe`, difficulty: 2},

    {city: `Cardiff`, name: `Wales`, difficulty: 2},
    {city: `Edinburgh`, name: `Scotland`, difficulty: 2},
    {city: `Belfast`, name: `Northern Ireland`, difficulty: 2}];