exports.flagsCountry = [
    {id: `AF`, name: `Afghanistan`, difficulty: 2},
    {id: `AX`, name: `Aland Islands`, difficulty: 3},
    {id: `AL`, name: `Albania`, difficulty: 2},
    {id: `DZ`, name: `Algeria`, difficulty: 1},
    {id: `AS`, name: `American Samoa`, difficulty: 4},
    {id: `AD`, name: `Andorra`, difficulty: 2},
    {id: `AO`, name: `Angola`, difficulty: 2},
    {id: `AI`, name: `Anguilla`, difficulty: 3},
    {id: `AQ`, name: `Antarctica`, difficulty: 1},
    {id: `AG`, name: `Antigua and Barbuda`, difficulty: 3},
    {id: `AR`, name: `Argentina`, difficulty: 1},
    {id: `AM`, name: `Armenia`, difficulty: 2},
    {id: `AW`, name: `Aruba`, difficulty: 3},
    {id: `AU`, name: `Australia`, difficulty: 0},
    {id: `AT`, name: `Austria`, difficulty: 1},
    {id: `AZ`, name: `Azerbaijan`, difficulty: 2},
   
    {id: `BS`, name: `Bahamas`, difficulty: 3},
    {id: `BH`, name: `Bahrain`, difficulty: 2},
    {id: `BD`, name: `Bangladesh`, difficulty: 1},
    {id: `BB`, name: `Barbados`, difficulty: 2},
    {id: `BY`, name: `Belarus`, difficulty: 2},
    {id: `BE`, name: `Belgium`, difficulty: 1},
    {id: `BZ`, name: `Belize`, difficulty: 2},
    {id: `BJ`, name: `Benin`, difficulty: 3},
    {id: `BM`, name: `Bermuda`, difficulty: 3},
    {id: `BT`, name: `Bhutan`, difficulty: 2},
    {id: `BO`, name: `Bolivia`, difficulty: 3},
    {id: `BA`, name: `Bosnia`, difficulty: 2},
    {id: `BW`, name: `Botswana`, difficulty: 3},
    {id: `BV`, name: `Bouvet Island`, difficulty: 4},
    {id: `BR`, name: `Brazil`, difficulty: 0},
    {id: `VG`, name: `British Virgin Islands`, difficulty: 4},
    {id: `IO`, name: `British Indian Ocean Territory`, difficulty: 4},
    {id: `BN`, name: `Brunei`, difficulty: 2},
    {id: `BG`, name: `Bulgaria`, difficulty: 1},
    {id: `BF`, name: `Burkina Faso`, difficulty: 3},
    {id: `BI`, name: `Burundi`, difficulty: 2},
    {id: `BQ`, name: `Bonaire`, difficulty: 3},
    
    {id: `KH`, name: `Cambodia`, difficulty: 2},
    {id: `CM`, name: `Cameroon`, difficulty: 2},
    {id: `CA`, name: `Canada`, difficulty: 0},
    {id: `CV`, name: `Cape Verde`, difficulty: 3},
    {id: `KY`, name: `Cayman Islands`, difficulty: 4},
    {id: `CF`, name: `Central African Republic`, difficulty: 3},
    {id: `TD`, name: `Chad`, difficulty: 3},
    {id: `CL`, name: `Chile`, difficulty: 1},
    {id: `CN`, name: `China`, difficulty: 0},
    {id: `HK`, name: `Hong Kong`, difficulty: 0},
    {id: `MO`, name: `Macau`, difficulty: 1},
    {id: `CX`, name: `Christmas Island`, difficulty: 3},
    {id: `CC`, name: `Cocos Keeling Islands`, difficulty: 3},
    {id: `CO`, name: `Colombia`, difficulty: 1},
    {id: `KM`, name: `Comoros`, difficulty: 2},
    {id: `CG`, name: `Congo`, difficulty: 2},
    {id: `CD`, name: `Democratic Republic of Congo`, difficulty: 1},
    {id: `CK`, name: `Cook Islands`, difficulty: 3},
    {id: `CR`, name: `Costa Rica`, difficulty: 2},
    {id: `CI`, name: `Ivory Coast`, difficulty: 3},
    {id: `HR`, name: `Croatia`, difficulty: 1},
    {id: `CU`, name: `Cuba`, difficulty: 1},
    {id: `CW`, name: `Curacao`, difficulty: 3},
    {id: `CY`, name: `Cyprus`, difficulty: 2},
    {id: `CZ`, name: `Czech Republic`, difficulty: 1},
    {id: `CP`, name: `Clipperton Island`, difficulty: 4},
    {id: `EA`, name: `Ceuta and Melilla`, difficulty: 4},
    {id: `IC`, name: `Canary Islands`, difficulty: 4},
    
    {id: `DK`, name: `Denmark`, difficulty: 1},
    {id: `DJ`, name: `Djibouti`, difficulty: 2},
    {id: `DM`, name: `Dominica`, difficulty: 2},
    {id: `DO`, name: `Dominican Republic`, difficulty: 2},
    {id: `DG`, name: `Diego Garcia`, difficulty: 4},
    
    {id: `EC`, name: `Ecuador`, difficulty: 2},
    {id: `EG`, name: `Egypt`, difficulty: 1},
    {id: `SV`, name: `El Salvador`, difficulty: 3},
    {id: `GQ`, name: `Equatorial Guinea`, difficulty: 3},
    {id: `ER`, name: `Eritrea`, difficulty: 2},
    {id: `EE`, name: `Estonia`, difficulty: 1},
    {id: `ET`, name: `Ethiopia`, difficulty: 1},
    {id: `EU`, name: `European Union`, difficulty: 1},
    
    {id: `FK`, name: `Falkland Islands`, difficulty: 4},
    {id: `FO`, name: `Faroe Islands`, difficulty: 3},
    {id: `FJ`, name: `Fiji`, difficulty: 3},
    {id: `FI`, name: `Finland`, difficulty: 1},
    {id: `FR`, name: `France`, difficulty: 0},
    {id: `GF`, name: `French Guiana`, difficulty: 4},
    {id: `PF`, name: `French Polynesia`, difficulty: 4},
    {id: `TF`, name: `French Southern Territories`, difficulty: 4},
    
    {id: `GA`, name: `Gabon`, difficulty: 3},
    {id: `GM`, name: `Gambia`, difficulty: 3},
    {id: `GE`, name: `Georgia`, difficulty: 2},
    {id: `DE`, name: `Germany`, difficulty: 0},
    {id: `GH`, name: `Ghana`, difficulty: 2},
    {id: `GI`, name: `Gibraltar`, difficulty: 2},
    {id: `GR`, name: `Greece`, difficulty: 1},
    {id: `GL`, name: `Greenland`, difficulty: 2},
    {id: `GD`, name: `Grenada`, difficulty: 3},
    {id: `GP`, name: `Guadeloupe`, difficulty: 4},
    {id: `GU`, name: `Guam`, difficulty: 2},
    {id: `GT`, name: `Guatemala`, difficulty: 3},
    {id: `GG`, name: `Guernsey`, difficulty: 4},
    {id: `GN`, name: `Guinea`, difficulty: 3},
    {id: `GW`, name: `Guinea Bissau`, difficulty: 3},
    {id: `GY`, name: `Guyana`, difficulty: 3},
    
    {id: `HT`, name: `Haiti`, difficulty: 2},
    {id: `HM`, name: `Heard Island and McDonald Island`, difficulty: 4},
    {id: `VA`, name: `Vatican City`, difficulty: 1},
    {id: `HN`, name: `Honduras`, difficulty: 2},
    {id: `HU`, name: `Hungary`, difficulty: 1},
    
    {id: `IS`, name: `Iceland`, difficulty: 1},
    {id: `IN`, name: `India`, difficulty: 0},
    {id: `ID`, name: `Indonesia`, difficulty: 1},
    {id: `IR`, name: `Iran`, difficulty: 0},
    {id: `IQ`, name: `Iraq`, difficulty: 1},
    {id: `IE`, name: `Ireland`, difficulty: 2},
    {id: `IM`, name: `Isle of Man`, difficulty: 2},
    {id: `IL`, name: `Israel`, difficulty: 1},
    {id: `IT`, name: `Italy`, difficulty: 0},
    
    {id: `JM`, name: `Jamaica`, difficulty: 1},
    {id: `JP`, name: `Japan`, difficulty: 0},
    {id: `JE`, name: `Jersey`, difficulty: 4},
    {id: `JO`, name: `Jordan`, difficulty: 2},
    
    {id: `KZ`, name: `Kazakhstan`, difficulty: 1},
    {id: `KE`, name: `Kenya`, difficulty: 2},
    {id: `KI`, name: `Kiribati`, difficulty: 3},
    {id: `KP`, name: `North Korea`, difficulty: 0},
    {id: `KR`, name: `South Korea`, difficulty: 0},
    {id: `KW`, name: `Kuwait`, difficulty: 2},
    {id: `KG`, name: `Kyrgyzstan`, difficulty: 3},
    
    {id: `LA`, name: `Laos`, difficulty: 3},
    {id: `LV`, name: `Latvia`, difficulty: 2},
    {id: `LB`, name: `Lebanon`, difficulty: 2},
    {id: `LS`, name: `Lesotho`, difficulty: 3},
    {id: `LR`, name: `Liberia`, difficulty: 2},
    {id: `LY`, name: `Libya`, difficulty: 2},
    {id: `LI`, name: `Liechtenstein`, difficulty: 3},
    {id: `LT`, name: `Lithuania`, difficulty: 2},
    {id: `LU`, name: `Luxembourg`, difficulty: 2},
    
    {id: `MK`, name: `North Macedonia`, difficulty: 3},
    {id: `MG`, name: `Madagascar`, difficulty: 2},
    {id: `MW`, name: `Malawi`, difficulty: 3},
    {id: `MY`, name: `Malaysia`, difficulty: 1},
    {id: `MV`, name: `Maldives`, difficulty: 3},
    {id: `ML`, name: `Mali`, difficulty: 3},
    {id: `MT`, name: `Malta`, difficulty: 2},
    {id: `MH`, name: `Marshall Islands`, difficulty: 3},
    {id: `MQ`, name: `Martinique`, difficulty: 4},
    {id: `MR`, name: `Mauritania`, difficulty: 3},
    {id: `MU`, name: `Mauritius`, difficulty: 3},
    {id: `YT`, name: `Mayotte`, difficulty: 4},
    {id: `MX`, name: `Mexico`, difficulty: 0},
    {id: `FM`, name: `Micronesia`, difficulty: 3},
    {id: `MD`, name: `Moldova`, difficulty: 3},
    {id: `MC`, name: `Monaco`, difficulty: 3},
    {id: `MN`, name: `Mongolia`, difficulty: 2},
    {id: `ME`, name: `Montenegro`, difficulty: 3},
    {id: `MS`, name: `Montserrat`, difficulty: 4},
    {id: `MA`, name: `Morocco`, difficulty: 1},
    {id: `MZ`, name: `Mozambique`, difficulty: 3},
    {id: `MM`, name: `Myanmar`, difficulty: 2},
    
    {id: `NA`, name: `Namibia`, difficulty: 3},
    {id: `NR`, name: `Nauru`, difficulty: 3},
    {id: `NP`, name: `Nepal`, difficulty: 1},
    {id: `NL`, name: `Netherlands`, difficulty: 0},
    {id: `NC`, name: `New Caledonia`, difficulty: 4},
    {id: `NZ`, name: `New Zealand`, difficulty: 1},
    {id: `NI`, name: `Nicaragua`, difficulty: 2},
    {id: `NE`, name: `Niger`, difficulty: 3},
    {id: `NG`, name: `Nigeria`, difficulty: 1},
    {id: `NU`, name: `Niue`, difficulty: 4},
    {id: `NF`, name: `Norfolk Island`, difficulty: 4},
    {id: `MP`, name: `Northern Mariana Islands`, difficulty: 4},
    {id: `NO`, name: `Norway`, difficulty: 1},
    
    {id: `OM`, name: `Oman`, difficulty: 2},
    
    {id: `PK`, name: `Pakistan`, difficulty: 1},
    {id: `PW`, name: `Palau`, difficulty: 2},
    {id: `PS`, name: `Palestine`, difficulty: 1},
    {id: `PA`, name: `Panama`, difficulty: 1},
    {id: `PG`, name: `Papua New Guinea`, difficulty: 3},
    {id: `PY`, name: `Paraguay`, difficulty: 2},
    
    {id: `PE`, name: `Peru`, difficulty: 2},
    {id: `PH`, name: `Philippines`, difficulty: 1},
    {id: `PN`, name: `Pitcairn Islands`, difficulty: 4},
    {id: `PL`, name: `Poland`, difficulty: 1},
    {id: `PT`, name: `Portugal`, difficulty: 1},
    {id: `PR`, name: `Puerto Rico`, difficulty: 2},
    
    {id: `QA`, name: `Qatar`, difficulty: 2},
    
    {id: `RE`, name: `Reunion`, difficulty: 4},
    {id: `RO`, name: `Romania`, difficulty: 1},
    {id: `RU`, name: `Russia`, difficulty: 0},
    {id: `RW`, name: `Rwanda`, difficulty: 3},
    
    {id: `BL`, name: `Saint Barthelemy`, difficulty: 4},
    {id: `SH`, name: `Saint Helena`, difficulty: 4},
    {id: `KN`, name: `Saint Kitts and Nevis`, difficulty: 3},
    {id: `LC`, name: `Saint Lucia`, difficulty: 3},
    {id: `MF`, name: `Saint Martin`, difficulty: 4},
    {id: `PM`, name: `Saint Pierre and Miquelon`, difficulty: 4},
    {id: `VC`, name: `Saint Vincent and the Grenadines`, difficulty: 4},
    {id: `WS`, name: `Samoa`, difficulty: 3},
    {id: `SM`, name: `San Marino`, difficulty: 2},
    {id: `ST`, name: `Sao Tome and Principe`, difficulty: 3},
    {id: `SA`, name: `Saudi Arabia`, difficulty: 1},
    {id: `SN`, name: `Senegal`, difficulty: 3},
    {id: `RS`, name: `Serbia`, difficulty: 1},
    {id: `SC`, name: `Seychelles`, difficulty: 2},
    {id: `SL`, name: `Sierra Leone`, difficulty: 3},
    {id: `SG`, name: `Singapore`, difficulty: 1},
    {id: `SK`, name: `Slovakia`, difficulty: 2},
    {id: `SI`, name: `Slovenia`, difficulty: 2},
    {id: `SB`, name: `Solomon Islands`, difficulty: 3},
    {id: `SO`, name: `Somalia`, difficulty: 2},
    {id: `ZA`, name: `South Africa`, difficulty: 1},
    {id: `GS`, name: `South Georgia and the South Sandwich Islands`, difficulty: 4},
    {id: `SS`, name: `South Sudan`, difficulty: 3},
    {id: `ES`, name: `Spain`, difficulty: 0},
    {id: `LK`, name: `Sri Lanka`, difficulty: 1},
    {id: `SD`, name: `Sudan`, difficulty: 2},
    {id: `SR`, name: `Suriname`, difficulty: 3},
    {id: `SJ`, name: `Svalbard and Jan Mayen`, difficulty: 4},
    {id: `SZ`, name: `eSwatini`, difficulty: 3},
    {id: `SE`, name: `Sweden`, difficulty: 1},
    {id: `CH`, name: `Switzerland`, difficulty: 0},
    {id: `SY`, name: `Syria`, difficulty: 1},
    
    {id: `TW`, name: `Taiwan`, difficulty: 1},
    {id: `TJ`, name: `Tajikistan`, difficulty: 3},
    {id: `TZ`, name: `Tanzania`, difficulty: 2},
    {id: `TH`, name: `Thailand`, difficulty: 1},
    {id: `TL`, name: `Timor Leste`, difficulty: 3},
    {id: `TG`, name: `Togo`, difficulty: 3},
    {id: `TK`, name: `Tokelau`, difficulty: 4},
  
    {id: `TO`, name: `Tonga`, difficulty: 3},
    {id: `TT`, name: `Trinidad and Tobago`, difficulty: 2},
    {id: `TN`, name: `Tunisia`, difficulty: 2},
    {id: `TR`, name: `Turkey`, difficulty: 0},
    {id: `TM`, name: `Turkmenistan`, difficulty: 3},
    {id: `TC`, name: `Turks and Caicos Islands`, difficulty: 4},
    {id: `TV`, name: `Tuvalu`, difficulty: 3},
    
    {id: `UG`, name: `Uganda`, difficulty: 2},
    {id: `UA`, name: `Ukraine`, difficulty: 1},
    {id: `AE`, name: `United Arab Emirates`, difficulty: 1},
    {id: `GB`, name: `United Kingdom`, difficulty: 0},
    {id: `US`, name: `United States of America`, difficulty: 0},
    {id: `UM`, name: `US Minor Outlying Islands`, difficulty: 4},
    {id: `UY`, name: `Uruguay`, difficulty: 2},
    {id: `UZ`, name: `Uzbekistan`, difficulty: 2},
    
    {id: `VU`, name: `Vanuatu`, difficulty: 3},
    {id: `VE`, name: `Venezuela`, difficulty: 2},
    {id: `VN`, name: `Vietnam`, difficulty: 1},
    {id: `VI`, name: `US Virgin Islands`, difficulty: 4},
    
    {id: `WF`, name: `Wallis and Futuna`, difficulty: 4},
    {id: `EH`, name: `Western Sahara`, difficulty: 3},
    
    {id: `YE`, name: `Yemen`, difficulty: 2},
    
    {id: `ZM`, name: `Zambia`, difficulty: 2},
    {id: `ZW`, name: `Zimbabwe`, difficulty: 2}];
  
exports.flagsHistory = [
    {id: `dere:685507759025815641`, name: `German Empire`, difficulty: 3},
    {id: `drre:685508236341674041`, name: `Nazi Germany`, difficulty: 1},
    {id: `golh:685508037481726068`, name: `Golden Horde`, difficulty: 4},
    {id: `hre:685508081307746340`, name: `Holy Roman Empire`, difficulty: 3},
    {id: `imbr:685507577437618229`, name: `Empire of Brazil`, difficulty: 3},
    
    {id: `mgem:685508191747833874`, name: `Mongol Empire`, difficulty: 3},
    {id: `ming:685508168075575343`, name: `Ming Dynasty`, difficulty: 3},
    {id: `osmn:685508383465406487`, name: `Ottoman Empire`, difficulty: 3},
    {id: `osun:685507370981392418`, name: `Austro-Hungarian Empire`, difficulty: 3},
    {id: `preu:685508416571047956`, name: `Prussia`, difficulty: 3},
    
    {id: `qing:685508452399054853`, name: `Qing Dynasty`, difficulty: 3},
    {id: `rhod:685508485965938781`, name: `Rhodesia`, difficulty: 4},
    {id: `timr:685508577716076547`, name: `Timurid Empire`, difficulty: 4},
    {id: `uksn:685508523181735982`, name: `United Kingdoms of Sweden and Norway`, difficulty: 4},
    {id: `ussr:685508637921247259`, name: `Soviet Union`, difficulty: 0},
    
    {id: `zair:685508704409354245`, name: `Zaire`, difficulty: 4},
    {id: `imes:685529621789409301`, name: `Spanish Empire`, difficulty: 3},
    {id: `maml:685529434803273759`, name: `Mamluk Sultanate`, difficulty: 4},
    {id: `safv:685535310524055579`, name: `Safavid Dynasty`, difficulty: 4},
    {id: `tuva:685535362025652235`, name: `Tannu Tuva`, difficulty: 4},
    
    {id: `rofr:685536711429849104`, name: `Kingdom of France`, difficulty: 3},
    {id: `roim:685537712610213888`, name: `Russian Empire`, difficulty: 3},
    {id: `svie:685538634153459726`, name: `South Vietnam`, difficulty: 4},
    {id: `theu:685541389056081943`, name: `Teutonic Order`, difficulty: 4},
    {id: `yugo:686624820024311854`, name: `Yugoslavia`, difficulty: 2},
    
    {id: `conf:686625675918311452`, name: `Confederate States of America`, difficulty: 2},
    {id: `ryuk:687787277593739308`, name: `Ryukyu`, difficulty: 4}];

exports.flagsUnrecognised = [
    {id: `trns:685508606535139355`, name: `Transnistria`, difficulty: 4},
    {id: `isis:685508139050598448`, name: `Islamic State of Iraq and Syria`, difficulty: 1},
    {id: `soma:685535211953586194`, name: `Somaliland`, difficulty: 4},
    {id: `trnc:685535405163937821`, name: `Northern Cyprus`, difficulty: 3},
    {id: `abkh:687406833819975736`, name: `Abkhazia`, difficulty: 4},
    {id: `rsos:687407449744867371`, name: `South Ossetia`, difficulty: 4}];