flags = [
  {id: "AF", name: "Afghanistan"},
  {id: "AX", name: "Aland Islands"},
  {id: "AL", name: "Albania"},
  {id: "DZ", name: "Algeria"},
  {id: "AS", name: "American Samoa"},
  {id: "AD", name: "Andorra"},
  {id: "AO", name: "Angola"},
  {id: "AI", name: "Anguilla"},
  {id: "AQ", name: "Antarctica"},
  {id: "AG", name: "Antigua and Barbuda"},
  {id: "AR", name: "Argentina"},
  {id: "AM", name: "Armenia"},
  {id: "AW", name: "Aruba"},
  {id: "AU", name: "Australia"},
  {id: "AT", name: "Austria"},
  {id: "AZ", name: "Azerbaijan"},
 
  {id: "BS", name: "Bahamas"},
  {id: "BH", name: "Bahrain"},
  {id: "BD", name: "Bangladesh"},
  {id: "BB", name: "Barbades"},
  {id: "BY", name: "Belarus"},
  {id: "BE", name: "Belgium"},
  {id: "BZ", name: "Belize"},
  {id: "BJ", name: "Benin"},
  {id: "BM", name: "Bermuda"},
  {id: "BT", name: "Bhutan"},
  {id: "BO", name: "Bolivia"},
  {id: "BA", name: "Bosnia"},
  {id: "BW", name: "Botswana"},
  {id: "BV", name: "Bouvet Island"},
  {id: "BR", name: "Brazil"},
  {id: "VG", name: "British Virgin Islands"},
  {id: "IO", name: "British Indian Ocean Territory"},
  {id: "BN", name: "Brunei Darussalam"},
  {id: "BG", name: "Bulgaria"},
  {id: "BF", name: "Burkina Faso"},
  {id: "BI", name: "Burundi"},
  
  {id: "KH", name: "Cambodia"},
  {id: "CM", name: "Cameroon"},
  {id: "CA", name: "Canada"},
  {id: "CV", name: "Cape Verde"},
  {id: "KY", name: "Cayman Islands"},
  {id: "CF", name: "Central African Republic"},
  {id: "TD", name: "Chad"},
  {id: "CL", name: "Chile"},
  {id: "CN", name: "China"},
  {id: "HK", name: "Hong Kong"},
  {id: "MO", name: "Macau"},
  {id: "CX", name: "Christmas Island"},
  {id: "CC", name: "Cocos Keeling Islands"},
  {id: "CO", name: "Colombia"},
  {id: "KM", name: "Comoros"},
  {id: "CG", name: "Congo"},
  {id: "CD", name: "Democratic Republic of Congo"},
  {id: "CK", name: "Cook Islands"},
  {id: "CR", name: "Costa Rica"},
  {id: "CI", name: "Ivory Coast"},
  {id: "HR", name: "Croatia"},
  {id: "CU", name: "Cuba"},
  {id: "CY", name: "Cyprus"},
  {id: "CZ", name: "Czech Republic"},
  
  {id: "DK", name: "Denmark"},
  {id: "DJ", name: "Djibouti"},
  {id: "DM", name: "Dominica"},
  {id: "DO", name: "Dominican Republic"},
  
  {id: "EC", name: "Ecuador"},
  {id: "EG", name: "Egypt"},
  {id: "SV", name: "El Salvador"},
  {id: "GQ", name: "Equatorial Guinea"},
  {id: "ER", name: "Eritrea"},
  {id: "EE", name: "Estonia"},
  {id: "ET", name: "Ethiopia"},
  
  {id: "FK", name: "Falkland Islands"},
  {id: "FO", name: "Faroe Islands"},
  {id: "FJ", name: "Fiji"},
  {id: "FI", name: "Finland"},
  {id: "FR", name: "France"},
  {id: "GF", name: "French Guiana"},
  {id: "PF", name: "French Polynesia"},
  {id: "TF", name: "French Southern Territories"},
  
  {id: "GA", name: "Gabon"},
  {id: "GM", name: "Gambia"},
  {id: "GE", name: "Georgia"},
  {id: "DE", name: "Germany"},
  {id: "GH", name: "Ghana"},
  {id: "GI", name: "Gibraltar"},
  {id: "GR", name: "Greece"},
  {id: "GL", name: "Greenland"},
  {id: "GD", name: "Grenada"},
  {id: "GP", name: "Guadeloupe"},
  {id: "GU", name: "Guam"},
  {id: "GT", name: "Guatemala"},
  {id: "GG", name: "Guernsey"},
  {id: "GN", name: "Guinea"},
  {id: "GW", name: "Guinea Bissau"},
  {id: "GY", name: "Guyana"},
  
  {id: "HT", name: "Haiti"},
  {id: "HM", name: "Heard Island and McDonald Island"},
  {id: "VA", name: "Vatican City"},
  {id: "HN", name: "Honduras"},
  {id: "HU", name: "Hungary"},
  
  {id: "IS", name: "Iceland"},
  {id: "IN", name: "India"},
  {id: "ID", name: "Indonesia"},
  {id: "IR", name: "Iran"},
  {id: "IQ", name: "Iraq"},
  {id: "IE", name: "Ireland"},
  {id: "IM", name: "Isle of Man"},
  {id: "IL", name: "Israel"},
  {id: "IT", name: "Italy"},
  {id: "JM", name: "Jamaica"},
  {id: "JP", name: "Japan"},
  {id: "JE", name: "Jersey"},
  {id: "JO", name: "Jordan"},
  {id: "KZ", name: "Kazahkstan"},
  {id: "KE", name: "Kenya"},
  {id: "KI", name: "Kiribati"},
  {id: "KP", name: "North Korea"},
  {id: "KR", name: "South Korea"},
  {id: "KW", name: "Kuwait"},
  {id: "KG", name: "Kyrgyzstan"},
  {id: "LA", name: "Laos"},
  {id: "LV", name: "Latvia"},
  {id: "LB", name: "Lebanon"},
  {id: "LS", name: "Lesotho"}];

burger = [
  "https://i.gifer.com/Qlsi.gif", 
  "https://media.giphy.com/media/EmSCxtcjQCmXK/giphy.gif", 
  "https://gif-free.com/uploads/posts/2018-01/1517419327_anime-girl-eating-burger.gif", 
  "https://i.gifer.com/nwL.gif", 
  "https://i.gifer.com/ElSx.gif", 
  "https://img.fireden.net/a/image/1486/57/1486574417193.gif",
  "https://cdn.discordapp.com/attachments/458082060607684608/478966167906549763/image.gif",
  "https://i.warosu.org/data/jp/img/0124/38/1409634459946.gif",
  "https://i.gifer.com/5MQq.gif"];

rape = [
  "https://img.4plebs.org/boards/sp/image/1405/27/1405279865972.gif", 
  "https://media1.tenor.com/images/dc7284a153bbc22dd2ddda022957e2be/tenor.gif", 
  "https://i.pinimg.com/originals/ce/41/9c/ce419c7a3723967df36b4a3c7ddfc8ac.gif", 
  "https://i.pinimg.com/originals/9c/11/f6/9c11f69bdf4517a6226f57875b163c20.gif", 
  "https://media.giphy.com/media/TxBXGd0h4kVS8/giphy.gif"];

help = "```/afk - Sets away from keyboard status\n/battle - Challenges another user to a battle!\n/burger - A burger a day keeps the doctor away!\n/coinflip - Flips a coin\n/dm - Sends DM to a user\n/help - Shows this help screen\n/invite - Invite me to your server!\n/nigger - Calculates a user's niggerness\n/ping - Pong\n/post - Posts a message\n/random - Generates a random number\n/rape - Rapes a user\n/s - Spits on grave```";

module.exports = {flags, burger, rape, help};
